AWS_REGION=us-east-1

AWS_ACCOUNT_ID=215520152570

ECR_REPOSITORY=215520152570.dkr.ecr.us-east-1.amazonaws.com/products-service

APPLICATION_EC2_PRIVATE_IP=172.31.17.99

APPLICATION_PORT=8082

RDS_HOST=products-db.cqnks84uonij.us-east-1.rds.amazonaws.com

RDS_PORT=5432

RDS_DATABASE=productsDB

RDS_USERNAME=jayanthgoud
